### PR TITLE
Displays the tree of upstream causes

### PR DESCRIPTION
**Pull request by dcoraboeuf**
With the 0.17 version of the Build Flow plug-in, the upstream causes of the Flow job itself are lost when looking at the build cause of a downstream job.

For example, if we have a build A triggering a build B triggering a FLOW, which itself launches a C job, I want the C job showing that it has been fired by FLOW, fired by B, fire by A. As we have when using basic project triggers.

My pull request appends to the existing `FlowCause` description the representation of the upstream causes (actually copied from the `Cause.UpstreamCause` `description.jelly` file).

I had to switch to Jelly for the `FlowCause.description` resource but it might be possible to use Groovy as well.

In the end, I can see the upstream cause:

image

### CODE REVIEW

**Comment by dnozay** [comment]
[Unit tests](https://wiki.jenkins-ci.org/display/JENKINS/Unit+Test) would be nice. The email-ext plugin has [some examples](https://github.com/jenkinsci/email-ext-plugin/blob/master/src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java)...

thank you!

**Comment by dcoraboeuf** [comment]
I'll add unit tests either tonight or tomorrow.

**Comment by dcoraboeuf** [comment]
Closed by mistake :(

**Comment by dcoraboeuf** [comment]
This PR has actually a problem - the Jenkins version (1.480) for this plug-in is not recent enough to get access the list of upstream causes from a `Cause.Upstream`. The access has been granted in a later version. I just know for sure that it works with Jenkins 1.584. I'll see later which minimal version of Jenkins we would need to make this work.

Just in case, could we consider upgrading the minimum Jenkins version for this plug-in?

**Comment by dcoraboeuf** [comment]
Access to the upstream causes has been introduced by the [0626f28965a773ffa73921561df1a9b5279f33bc|https://github.com/jenkinsci/jenkins/commit/0626f28965a773ffa73921561df1a9b5279f33bc] commit in Jenkins and is available from version 1.482 and onward.

I suggest we upgrade at least to this version or to next LTS version (1.509.1)

**Comment by dcoraboeuf** [comment]
Hi Damien, I've added a unit test and taken into account your remarks. I finally chose to upgrade Jenkins version to 1.482 (from 1.480). This is just enough to get the support for the `Cause.UpstreamCause#getUpstreamCauses()` method.

**Comment by daniel-beck** [comment]
> I finally chose to upgrade Jenkins version to 1.482 (from 1.480).

It is generally preferable to use LTS releases as parent versions to limit the number of different versions in use, see https://wiki.jenkins-ci.org/display/JENKINS/Plugin+Report+Card

For stats, see e.g. http://stats.jenkins-ci.org/plugin-installation-trend/installations.json — less than 2% of known installations use a version between 1.482 and 1.509.1.

**Comment by dcoraboeuf** [comment]
I'll upgrade to 1.509.1 then.

**Comment by dcoraboeuf** [comment]
I've upgraded the minimal version to the earliest LTS version after the minimal 1.482 version: 1.509.1.

**Comment by dcoraboeuf** [comment]
Thanks Damien. Do you know if I can expect a new release soon?

**Comment by dnozay** [comment]
working on it... tests are taking some time.

**Comment by dnozay** [comment]
done. thanks for the changes.

**Comment by dcoraboeuf** [comment]
Thanks for the release. Much appreciated.

**Pull request merged**
