### PR TITLE
JENKINS-34516 Moving FlowDownStreamRunDeclarer.java from Build-Flow-Plugin to BuildGraph-View

### PR DESCRIPTION
**Pull request by pskumar448**
As this file most functionality belongs to buildgraph-view.

### CODE REVIEW

**Comment by rodrigc** [comment]
Merged https://github.com/jenkinsci/build-flow-plugin/commit/908af0e024e604651a6a7cf709e5ddda32d6034b

**Comment by rodrigc** [comment]
@pskumar448 I released build-flow-plugin 0.19.  Please try it.

**Comment by rodrigc** [comment]
Can your changes to buildgraph-view be used even if I am not using build-flow-plugin?
For example, can I use buildgraph-view with pipeline-plugin?

**Comment by pskumar448** [comment]
Yes, It works and will get pipeline.

**Comment by rodrigc** [comment]
Nice job!

**Comment by rodrigc** [comment]
Jenkins developers seem to be putting effort into this plugin: https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Stage+View+Plugin
but good you are fixing buildgraph-view for existing users.

**Comment by rodrigc** [comment]
@pskumar448 I've been getting some reports about UI problems in build-flow in Jenkins2: https://issues.jenkins-ci.org/browse/JENKINS-34961  
Any ideas?  You know more about UI than I do for these plugins.
Thanks.

**Comment by pskumar448** [comment]
Hi Craig,
Let me reproduce the issue and will let you know if I can figure out a
solution.

Regards,
Suresh

On Sun, Jun 5, 2016 at 8:32 AM, Craig Rodrigues <notifications@github.com>
wrote:

> @pskumar448 <https://github.com/pskumar448> I've been getting some
> reports about UI problems in build-flow in Jenkins2:
> https://issues.jenkins-ci.org/browse/JENKINS-34961
>
> Any ideas? You know more about UI than I do for these plugins.
> Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkinsci/build-flow-plugin/pull/74#issuecomment-223790356>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIMGl3QjjFBNxQxg7J2NY5Z6qjkNbLUXks5qIjwrgaJpZM4IZb1L>
> .
>



-- 
- Suresh.

**Comment by pskumar448** [comment]
Hi Craig,
Fix for the above issue submitted as PR(
https://github.com/jenkinsci/build-flow-plugin/pull/75), validate the fix
and plan for release.

-Suresh

On Sun, Jun 5, 2016 at 8:32 AM, Craig Rodrigues <notifications@github.com>
wrote:

> @pskumar448 <https://github.com/pskumar448> I've been getting some
> reports about UI problems in build-flow in Jenkins2:
> https://issues.jenkins-ci.org/browse/JENKINS-34961
>
> Any ideas? You know more about UI than I do for these plugins.
> Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkinsci/build-flow-plugin/pull/74#issuecomment-223790356>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIMGl3QjjFBNxQxg7J2NY5Z6qjkNbLUXks5qIjwrgaJpZM4IZb1L>
> .
>



-- 
- Suresh.

**Pull request closed without merging**
