### PR TITLE
JENKINS 34961 Build flow sections created in older Jenkins versions disappeared in Jenkins 2.x

### PR DESCRIPTION
**Pull request by pskumar448**

### CODE REVIEW

**Comment by pskumar448** [comment]
@rodrigc 
Fixed JENKINS-34961 issue of disappearing DSL section when upgraded from old Jenkins version to Jenkins 2.x
Validate the fix and plan for release.

**Comment by kguelzau** [comment]
thank's a lot :+1:

**Comment by pskumar448** [comment]
@rodrigc 
Is this issue verified and working as expected, waiting for the feedback. Pls let me know.

**Comment by rodrigc** [comment]
@pskumar448 I am also waiting for feedback

**Comment by pskumar448** [comment]
Fix has been released in last release. So closing this PR.

**Pull request closed without merging**
