### PR TITLE
Use NamingThreadPool for parallel() statement

### PR DESCRIPTION
**Pull request by olivergondza**

### CODE REVIEW

**Comment by dnozay** [comment]
@olivergondza - tests failed in the code path you changed.

**Comment by olivergondza** [comment]
@dnozay yes, it broke with code dependency bump. For now I failed to fix or even understand what `ConcurrencyTest.testConcurrencyWithNonConcurrentDownstream` does.

**Comment by olivergondza** [comment]
I am proposing an alternative that does not require core version bump...

**Comment by dnozay** [comment]
thanks!

**Pull request merged**
